UD19 - Update 1.3
Fix missing data folders - modules were missing critical XML files

- Fixed .gitignore to allow module data/ folders
  * Root .gitignore: changed data/ to /data/ (only exclude root data folder)
  * custom_addons/.gitignore: removed data/ exclusion completely
  * Module data/ folders contain XML/CSV data files, NOT database files

- Added missing data folders for all modules:
  * vpa_sku_generator/data/sequence.xml (was causing install error)
  * vpa_sku_generator/data/product_actions.xml
  * vpa_document_layout/data/report_layout.xml
  * vpa_document_layout/data/default_config.xml
  * flow_cafe_product_label/data/custom_dymo_label_size.xml
  * garazd_product_label_pro/data/* (5 files)

This fixes the error:
FileNotFoundError: [Errno 2] No such file or directory:
'/home/odoo/src/user/custom_addons/vpa_sku_generator/data/sequence.xml'